# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Flow_config = debug
  Sandbox_config = debug
endif
ifeq ($(config),release)
  Flow_config = release
  Sandbox_config = release
endif

PROJECTS := Flow Sandbox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Flow:
ifneq (,$(Flow_config))
	@echo "==== Building Flow ($(Flow_config)) ===="
	@${MAKE} --no-print-directory -C Flow -f Makefile config=$(Flow_config)
endif

Sandbox: Flow
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C Flow -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Flow"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"