#pragma once 

#define CRUX_MOUSE_BUTTON_1         0
#define CRUX_MOUSE_BUTTON_2         1
#define CRUX_MOUSE_BUTTON_3         2
#define CRUX_MOUSE_BUTTON_4         3
#define CRUX_MOUSE_BUTTON_5         4
#define CRUX_MOUSE_BUTTON_6         5
#define CRUX_MOUSE_BUTTON_7         6
#define CRUX_MOUSE_BUTTON_8         7
#define CRUX_MOUSE_BUTTON_LAST      CRUX_MOUSE_BUTTON_8
#define CRUX_MOUSE_BUTTON_LEFT      CRUX_MOUSE_BUTTON_1
#define CRUX_MOUSE_BUTTON_RIGHT     CRUX_MOUSE_BUTTON_2
#define CRUX_MOUSE_BUTTON_MIDDLE    CRUX_MOUSE_BUTTON_3