#pragma once 

#define SAGE_MOUSE_BUTTON_1         0
#define SAGE_MOUSE_BUTTON_2         1
#define SAGE_MOUSE_BUTTON_3         2
#define SAGE_MOUSE_BUTTON_4         3
#define SAGE_MOUSE_BUTTON_5         4
#define SAGE_MOUSE_BUTTON_6         5
#define SAGE_MOUSE_BUTTON_7         6
#define SAGE_MOUSE_BUTTON_8         7
#define SAGE_MOUSE_BUTTON_LAST      SAGE_MOUSE_BUTTON_8
#define SAGE_MOUSE_BUTTON_LEFT      SAGE_MOUSE_BUTTON_1
#define SAGE_MOUSE_BUTTON_RIGHT     SAGE_MOUSE_BUTTON_2
#define SAGE_MOUSE_BUTTON_MIDDLE    SAGE_MOUSE_BUTTON_3